### ISSUE TITLE
Support for OCP 3.11

### ISSUE THREAD

**Issue by klenkes74** [redhat-cop/egressip-ipam-operator#33]
Hi,

we need to implement a similar solution for OCP 3.11 - would you accept a branch for OCP3 as contribution or should we fork-and-run?

We would prefer to contribute to your operator.

bye,
   Roland Lichti (on behalf of the DB Systel GmbH)

**Comment by raffaelespazzoli** [comment]
Hi Roland, 
I would love such a contribution.
Let's discuss a design that would allow the same code to run on both clusters.

**Comment by klenkes74** [comment]
Hi Rafaele,
I think, the biggest change is in detecting the infrastructure. AWS handling is the same, OCP-EgressIP-handling should not be different.

Only reading the configuration during startup should differ (well I have to check the code - I will start today to analyse it. Would you prefer a branch or should the code for both versions should be in the operator and can be switched (or even autoswitch via fallback to OCP3 when OCP4 discovery does not work).

bye,
   Roland

PS: should we discuss here or via mail/other means?

**Comment by raffaelespazzoli** [comment]
@klenkes74 please write to me here: rspazzol@redhat.com
we could have a design session.

**Comment by raffaelespazzoli** [comment]
closing this. The decision was to start a new operator the a complete new codebase to support 3.x. This codebase will not support 3.x as of now.
