### ISSUE TITLE
OKD4 example: first usage

### ISSUE THREAD

**Issue by Boran** [redhat-cop/egressip-ipam-operator#35]
I've just started playing with okd4 and came across this operator as the way to do egress Ips.

I created the egressip-ipam-operator project and deployed using the "Deploying directly with manifests" method from the README.

Also created the example-egressipam instance of EgressIPAM, which I understand is used by the egressip-ipam-operator pod to define what Ips are managed.

When Starting egressip-ipam-operator the pod logs gives

```
{"level":"info","ts":1595936784.3756962,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"namespace-controller","worker count":1}

{"level":"error","ts":1595936786.5877843,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"HostSubnet.network.openshift.io","error":"no matches for kind \"HostSubnet\" in version \"network.openshift.io/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/source/source.go:104\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/manager/internal.go:473"}

{"level":"error","ts":1595936786.5880451,"logger":"cmd","msg":"Manager exited non-zero","error":"no matches for kind \"HostSubnet\" in version \"network.openshift.io/v1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/home/travis/gopath/src/github.com/redhat-cop/egressip-ipam-operator/cmd/manager/main.go:147\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.linux.amd64/src/runtime/proc.go:203"}
```
it talks about "HostSubnet", but in the OKD4 i've not hostsubnet or netnamespace objects (as in V3.11)
```
oc get hostsubnet
error: the server doesn't have a resource type "hostsubnet"
oc get netnamespace
error: the server doesn't have a resource type "netnamespace"
```

Yet on docs such as https://docs.openshift.com/container-platform/4.5/networking/openshift_sdn/assigning-egress-ips.html and  https://examples.openshift.pub/networking/egress-ip/ one still talks about these objects. 
Are those docs out of date for v4 or am I missing some basic building block here? 
Any suggestions welcome :-)

**Comment by raffaelespazzoli** [comment]
I haven't tested OKD, it's weird that they don't have those objects. They are integral part of the OCP SDN, make sure it's deployed.
There is nothing I can do about it, if those CRDs are not deployed or used by OKD.

**Comment by Boran** [comment]
Yes you are right, on openshift4 they exist. Must be missing something in OKD4.
So testing on ocs4 then.
The example example-egressipam is also applied in the egressip-ipam-operator namespace?

Starts ok:
{"level":"info","ts":1595945699.6692455,"logger":"egressipam-controller","msg":"Reconciling EgressIPAM","Request.Namespace":"","Request.Name":"example-egressipam"}

In your example-egressipam example, "reservedIPs" is to stop certains IPS witing the CIDR being used, i.e. they would be manually assigned with egressip-ipam-operator.redhat-cop.io/egressips to a namespace?

And to assign a node for egress, label it with:
oc label node node1.example.net topologyLabel=egressGateway
and then the IPs should be visible with "oc get hostsubnet" ?

I'm still missing a few parts to the puzzle.

**Comment by raffaelespazzoli** [comment]
`In your example-egressipam example, "reservedIPs" is to stop certains IPS witing the CIDR being used, i.e. they would be manually assigned with egressip-ipam-operator.redhat-cop.io/egressips to a namespace?`

no the idea is that those IPs are reserved for other Machines in the same subnet/CIDR.

the nodes managed by an EgressIPAM CR depends on the labelSelector you define. The topology label instead determines to which CIDR the node belongs, as there can be more than one.

once an egress IP is assigned to a node, yes, you'll see it in the hostsubnet resource.

how egress IPs work is documented here: https://docs.openshift.com/container-platform/4.5/networking/openshift_sdn/assigning-egress-ips.html

**Comment by raffaelespazzoli** [comment]
@Boran can I close this?

**Comment by Boran** [comment]
Yes, thanks.
