### ISSUE TITLE
Specify Red Hat Community of Practice in CSV

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/egressip-ipam-operator#36]
To align the CoP operators, update the `provider` field in the CSV to the following:

```
  provider:
    name: Red Hat Community of Practice
```

**Comment by motaparthipavankumar** [comment]
Looks like this is already taken care by in this [PR](https://github.com/redhat-cop/egressip-ipam-operator/pull/41/commits/76fc281f1cb351b2c500cca9b2c531be463282d3).

**Comment by sabre1041** [comment]
@raffaelespazzoli good to close this?
