### ISSUE TITLE
aws IP address assignment collides with AWS resources allocated on the subnet

### ISSUE THREAD

**Issue by rguilme1** [redhat-cop/egressip-ipam-operator#43]
With the dynamic creation of Elastic Load Balancer and other resources where IP addresses are assigned by AWS from the subnet, it can cause issues when new projects are created that request egress ips from the egressip-ipam-operator.   The reservedIPs list is not sufficient in this case as new resources can be created at any time.

Would like the operator to dynamically check for IP addresses in use within the subnets prior to assigning an address.

This is a sample inquiry that we use to build the reservedIPs list that may be considered:

aws ec2 describe-network-interfaces --region us-east-1 | jq  -r '.NetworkInterfaces[].PrivateIpAddresses[0].PrivateIpAddress' |sort

**Comment by raffaelespazzoli** [comment]
The operator should already be doing that. Are you seeing that it doesn't
work for you

**Comment by klenkes74** [comment]
It could be a race condition between collecting the cloud provider data and assigning the ips. Should happen real seldom but can happen.
