### ISSUE TITLE
egressip-ipam-operator-controller-manager fails on OVN-Kubernetes

### ISSUE THREAD

**Issue by chrbac87** [redhat-cop/egressip-ipam-operator#66]
Is OVN supported?

Error from pod during egressip-ipam-operator-controller-manager deployment after installing the operator: 
`ERROR	setup	problem running manager	{"error": "no matches for kind \"HostSubnet\" in version \"network.openshift.io/v1\""}`

**Comment by raffaelespazzoli** [comment]
OVN is not supported and we have no plans at this point to do. The idea was to see how that feature was shaping up before committing time to it. Contributions would be welcome.

**Comment by ctrought** [comment]
> OVN is not supported and we have no plans at this point to do. The idea was to see how that feature was shaping up before committing time to it. Contributions would be welcome.

Hi @raffaelespazzoli, is this still the case? I read here https://github.com/redhat-cop/egressip-ipam-operator/issues/53 that OVN should be supported, but above comment which is newer leaves me a bit confused as to whether egress ipam operator supports both SDN and OVN clusters or only SDN. Seeing as OVN is the new default as of 4.8 (i think) it would be great to have OVN support if it is not already there.

**Comment by raffaelespazzoli** [comment]
I'm still in wait and see mode. What I don't understand is how the egressip feature works in the cloud. Do you know?

**Comment by ctrought** [comment]
> I'm still in wait and see mode. What I don't understand is how the egressip feature works in the cloud. Do you know?

Ok thank you. Yeah I am not too sure about that either. Currently we are leveraging egress for on-prem bare metal installs (platform: none).

**Comment by aelbarkani** [comment]
any update on having this operator work for OVN ?
