### ISSUE TITLE
Openshift in disconnected network installation support

### ISSUE THREAD

**Issue by yeneryumlu** [redhat-cop/egressip-ipam-operator#68]
We are using Openshift in disconnected network and using OLM on restricted network as explained in the following documentation.
https://docs.openshift.com/container-platform/4.6/operators/admin/olm-restricted-networks.html

egress-ipam-operator does not work on this restricted network topology. Is it possible to add support for this situation?

**Comment by raffaelespazzoli** [comment]
we are thinking about it, we don't have an ETA as of now. I'd recommend using the help based installation for disconnected environment where you can control the image you use.

**Comment by yeneryumlu** [comment]
We used helm to install the operator and it worked.
thank you all for the code.

**Comment by raffaelespazzoli** [comment]
closed by #79
