### ISSUE TITLE
Usage of different container regsitries for the same Image

### ISSUE THREAD

**Issue by thomasGusenleitner** [redhat-cop/egressip-ipam-operator#71]
Hi,

the source of the kube-rbac-proxy sidecar image is not consistent. 

config/default/manager_auth_proxy_patch.yaml  --> gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
config/helmchart/templates/manager.yaml --> quay.io/coreos/kube-rbac-proxy:v0.5.0

Unfortunately gcr.io is not allowed in my environment and the switch to gcr.io has blocked the operatore update to version 1.0.7

it would be great if it is possible to use only one registry or to provide a possibility to configure the image sources

regards,
Thomas

**Comment by raffaelespazzoli** [comment]
yes, I agree. 
@trevorbox any comments?

**Comment by trevorbox** [comment]
> yes, I agree.
> @trevorbox any comments?

Looks like this is the default created when the operator-sdk originally initialized the project.

For example...

```sh
operator-sdk init --domain example.com --repo github.com/example/memcached-operator
```

Makes sense to me to make this quay.io instead for consistency.

**Comment by trevorbox** [comment]
@raffaelespazzoli it seems that quay.io/coreos/kube-rbac-proxy:v0.5.0 is the latest but the upstream project
https://github.com/brancz/kube-rbac-proxy provides newer versions in quay.io/brancz/kube-rbac-proxy
We could try quay.io/brancz/kube-rbac-proxy:v0.8.0 to match what the operator-sdk v1.5.0 defaults to.

**Comment by trevorbox** [comment]
@sabre1041 - I tested _quay.io/openshift/origin-kube-rbac-proxy:latest_. Appears to work.
For now we will use _quay.io/coreos/kube-rbac-proxy:v0.5.0_ until we decide on more up-to-date approach.

**Comment by sabre1041** [comment]
That sounds like a good approach until we determine the longterm solution

**Comment by sabre1041** [comment]
@thomasGusenleitner new version of the operator has been released and should be available

**Comment by trevorbox** [comment]
There is a registry.redhat.io/openshift4/ose-kube-rbac-proxy image but that would require authentication.

**Comment by trevorbox** [comment]
@raffaelespazzoli can we reopen this issue to track final solution?
