### ISSUE TITLE
Cloud credentials for AWS

### ISSUE THREAD

**Issue by jwilms1971** [redhat-cop/egressip-ipam-operator#87]
When I tried to deploy the EgressIPAM CRD to my ROSA STS cluster it yielded the following message

Secret "egress-ipam-operator-cloud-credentials" not found.

I then created a secret for an admin-privileged user as follows:

echo "aws_access_key_id = $AWS_ID\naws_secret_access_key = $AWS_KEY" \ > /tmp/credentials
oc -namespace egress-ipam-operator \
   create secret generic egress-ipam-operator-cloud-credentials \
   --from-file=credentials=/tmp/credentials

The following message was then reported by the CRD:

unable to find key aws_access_key_id in secret &Secret{ObjectMeta:{egress-ipam-operator-cloud-credentials  egressip-ipam-operator  cc0d51f6-3575-4637-bde0-e0f0397409d7 146384 0 2022-01-10 08:30:50 +0000 UTC <nil> <nil> map[] map[] [] []  [{kubectl-create Update v1 2022-01-10 08:30:50 +0000 UTC FieldsV1 {"f:data":{".":{},"f:credentials":{}},"f:type":{}}}]},Data:map[string][]byte{credentials: [97 119 115 95 97 99 99 101 115 115 95 107 101 121 95 105 100 32 61 32 65 75 73 65 90 73 68 66 73 75 73 67 83 85 75 52 72 71 69 68 10 97 119 115 95 115 101 99 114 101 116 95 97 99 99 101 115 115 95 107 101 121 32 61 32 43 56 105 83 117 108 105 97 86 56 81 103 108 109 56 97 54 53 56 108 79 115 109 86 106 54 89 117 54 84 56 122 73 85 81 116 120 104 83 68 10],},Type:Opaque,StringData:map[string]string{},Immutable:nil,}

Please advise.

**Comment by raffaelespazzoli** [comment]
I believe you have to use the form:
oc create secret generic my-secret
--from-literal=aws_access_key_id=$AWS_ID
--from-literal=naws_secret_access_key=$AWS_KEY

**Comment by jwilms1971** [comment]
Confirmed. Thanks.
